{
  "formatVersion": "1.1",
  "component": {
    "group": "net.touchcapture.qr.flutterqr",
    "module": "qr_code_scanner_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_release-1.0.aar",
          "url": "qr_code_scanner_release-1.0.aar",
          "size": 36343,
          "sha512": "f741e45399682611c8163205fd3e322683b4b73e0dea25a6b6b6abd3f2e1d69ba79cb3ac0b0f724e1624192b0787e61f18a2f8ba013bcb1e0dfda0a7aa9d33e9",
          "sha256": "d02602b4cc1e38c969c37b03cdda8db1503001ee405678bce87d0b860f7d6ae6",
          "sha1": "327651d8ec8281e13e184d9ceb954d8647c14567",
          "md5": "21009695e93b0d4f848f5c48689475b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_release-1.0.aar",
          "url": "qr_code_scanner_release-1.0.aar",
          "size": 36343,
          "sha512": "f741e45399682611c8163205fd3e322683b4b73e0dea25a6b6b6abd3f2e1d69ba79cb3ac0b0f724e1624192b0787e61f18a2f8ba013bcb1e0dfda0a7aa9d33e9",
          "sha256": "d02602b4cc1e38c969c37b03cdda8db1503001ee405678bce87d0b860f7d6ae6",
          "sha1": "327651d8ec8281e13e184d9ceb954d8647c14567",
          "md5": "21009695e93b0d4f848f5c48689475b1"
        }
      ]
    }
  ]
}
