{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-1.0.aar",
          "url": "flutter_local_notifications_debug-1.0.aar",
          "size": 78936,
          "sha512": "faf9a90ef7490ba3e149ee9094bd616402359ac3964c74beb10c9410fd0c9e8ba8d5877f8feb141888f7e5056d0f804f65b637a153e8e5f7e48919e86e90a82f",
          "sha256": "1aae0acea1b5519dc34d8af3e6e3d8a5215798b226719988967bc8cec685b228",
          "sha1": "12bd5f25c9cc979a99a07e874003c7bdd6bd3b87",
          "md5": "7bcf79c3263c7cc78417eb1c72d39b72"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-1.0.aar",
          "url": "flutter_local_notifications_debug-1.0.aar",
          "size": 78936,
          "sha512": "faf9a90ef7490ba3e149ee9094bd616402359ac3964c74beb10c9410fd0c9e8ba8d5877f8feb141888f7e5056d0f804f65b637a153e8e5f7e48919e86e90a82f",
          "sha256": "1aae0acea1b5519dc34d8af3e6e3d8a5215798b226719988967bc8cec685b228",
          "sha1": "12bd5f25c9cc979a99a07e874003c7bdd6bd3b87",
          "md5": "7bcf79c3263c7cc78417eb1c72d39b72"
        }
      ]
    }
  ]
}
