{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_profile-1.0.aar",
          "url": "flutter_local_notifications_profile-1.0.aar",
          "size": 74558,
          "sha512": "9dab4dfb6cda8f3c8bbbe95878b08b2395e00df6bab71a2865594f93fe25e332245e2de44653e270c911502b6a244e1d0a08f5484d808fa8baa2c5890dc66ff5",
          "sha256": "c63d11dbdb149777141295547163ba50f918763e1765366fbc20c43394cec326",
          "sha1": "2f7b9de9dc21700fdd6920c2a867fa0e304a8494",
          "md5": "0bf7aeb99f4a6229e4045bd601f2e2c7"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_profile-1.0.aar",
          "url": "flutter_local_notifications_profile-1.0.aar",
          "size": 74558,
          "sha512": "9dab4dfb6cda8f3c8bbbe95878b08b2395e00df6bab71a2865594f93fe25e332245e2de44653e270c911502b6a244e1d0a08f5484d808fa8baa2c5890dc66ff5",
          "sha256": "c63d11dbdb149777141295547163ba50f918763e1765366fbc20c43394cec326",
          "sha1": "2f7b9de9dc21700fdd6920c2a867fa0e304a8494",
          "md5": "0bf7aeb99f4a6229e4045bd601f2e2c7"
        }
      ]
    }
  ]
}
