{
  "formatVersion": "1.1",
  "component": {
    "group": "net.touchcapture.qr.flutterqr",
    "module": "qr_code_scanner_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_profile-1.0.aar",
          "url": "qr_code_scanner_profile-1.0.aar",
          "size": 36361,
          "sha512": "d1278529c4e63af8d651e994c1bd456a987abc20b2b01699d4e9a4adecff800ba36e89c9cdb05e4bf907413341730428c833235c49241bc2b384af59265cad3f",
          "sha256": "368fa95160bbf10613940ac507805cb746dbf349899ba78aae456ae438b55f74",
          "sha1": "593157a8bf6b22427fa9a8931bfa1f88fedf65cc",
          "md5": "bcb591cdc44c4dcc45d384c832a1c0cd"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_profile-1.0.aar",
          "url": "qr_code_scanner_profile-1.0.aar",
          "size": 36361,
          "sha512": "d1278529c4e63af8d651e994c1bd456a987abc20b2b01699d4e9a4adecff800ba36e89c9cdb05e4bf907413341730428c833235c49241bc2b384af59265cad3f",
          "sha256": "368fa95160bbf10613940ac507805cb746dbf349899ba78aae456ae438b55f74",
          "sha1": "593157a8bf6b22427fa9a8931bfa1f88fedf65cc",
          "md5": "bcb591cdc44c4dcc45d384c832a1c0cd"
        }
      ]
    }
  ]
}
