{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fpt.isc.mobimap_plugin",
    "module": "mobimap_plugin_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobimap_plugin_profile-1.0.aar",
          "url": "mobimap_plugin_profile-1.0.aar",
          "size": 466526,
          "sha512": "69650d1eec4a0a6c8a30c23281aec9c4251d7ad37be7c81b8c8f1896de96c0c6dc116d5ff6d50867d82a5ccb2d02d43d33428154971e896a9beddb0f9baf4cac",
          "sha256": "db7641f1aa8be1e6b616a32ff6730b4a2b60821f0a42c1c43bb7e4c0ad832366",
          "sha1": "c168e6d6e953836fa8d60a41ef6a310930adaf13",
          "md5": "5cc2c46979df32782def7fc66df5be59"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobimap_plugin_profile-1.0.aar",
          "url": "mobimap_plugin_profile-1.0.aar",
          "size": 466526,
          "sha512": "69650d1eec4a0a6c8a30c23281aec9c4251d7ad37be7c81b8c8f1896de96c0c6dc116d5ff6d50867d82a5ccb2d02d43d33428154971e896a9beddb0f9baf4cac",
          "sha256": "db7641f1aa8be1e6b616a32ff6730b4a2b60821f0a42c1c43bb7e4c0ad832366",
          "sha1": "c168e6d6e953836fa8d60a41ef6a310930adaf13",
          "md5": "5cc2c46979df32782def7fc66df5be59"
        }
      ]
    }
  ]
}
