{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.crashlytics",
    "module": "firebase_crashlytics_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_crashlytics_debug-1.0.aar",
          "url": "firebase_crashlytics_debug-1.0.aar",
          "size": 17192,
          "sha512": "ee766e1baad185a4e4e018faa52634ec46b3b289e4c3707320580ba4d9ba9f9eec72267599edebb33bc9a50b74cfbfe29baf7f5cc9d7cae54be4e9d90bdca6ac",
          "sha256": "a4e7c378a741346e8ffe4317fe3e467a01cc813a4e6e266fa3e73aaac852845e",
          "sha1": "2d5177df19e239dd4c349771b01db961a3de15e0",
          "md5": "a554a89ad880d39edeea12c28f2eea4c"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "30.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_crashlytics_debug-1.0.aar",
          "url": "firebase_crashlytics_debug-1.0.aar",
          "size": 17192,
          "sha512": "ee766e1baad185a4e4e018faa52634ec46b3b289e4c3707320580ba4d9ba9f9eec72267599edebb33bc9a50b74cfbfe29baf7f5cc9d7cae54be4e9d90bdca6ac",
          "sha256": "a4e7c378a741346e8ffe4317fe3e467a01cc813a4e6e266fa3e73aaac852845e",
          "sha1": "2d5177df19e239dd4c349771b01db961a3de15e0",
          "md5": "a554a89ad880d39edeea12c28f2eea4c"
        }
      ]
    }
  ]
}
