{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fpt.isc.mobimap_plugin",
    "module": "mobimap_plugin_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobimap_plugin_release-1.0.aar",
          "url": "mobimap_plugin_release-1.0.aar",
          "size": 466510,
          "sha512": "2ba3da8027d012b5bd35b394bf0f79ae0c45f497775acc369115d6e65b906993202d37ae284f86b4100d7529b7ae00542805a9077d5494616052e16b2c9d55e0",
          "sha256": "b50f4ad477104e6f17d2e6d6744f0d9608860997ac3cc5a3ac47781232f83697",
          "sha1": "3571cf844f9526b1a66120a6170368b5a9cd6739",
          "md5": "cd6d7d4113a841d5b5e2a107c4b3d19d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobimap_plugin_release-1.0.aar",
          "url": "mobimap_plugin_release-1.0.aar",
          "size": 466510,
          "sha512": "2ba3da8027d012b5bd35b394bf0f79ae0c45f497775acc369115d6e65b906993202d37ae284f86b4100d7529b7ae00542805a9077d5494616052e16b2c9d55e0",
          "sha256": "b50f4ad477104e6f17d2e6d6744f0d9608860997ac3cc5a3ac47781232f83697",
          "sha1": "3571cf844f9526b1a66120a6170368b5a9cd6739",
          "md5": "cd6d7d4113a841d5b5e2a107c4b3d19d"
        }
      ]
    }
  ]
}
