{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fpt.isc.mobimap_plugin",
    "module": "mobimap_plugin_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobimap_plugin_debug-1.0.aar",
          "url": "mobimap_plugin_debug-1.0.aar",
          "size": 469234,
          "sha512": "5640a56735045f7c86f5ce30589171e98079d92504fec5ecd6e6585be67c1993ad4eca25da1ca5d2d7c08a5f4668601472467d8d4deb1ee5d3ba04cf45ff312d",
          "sha256": "924240212eb01db887900d4da4bb6784bbe4017ee1156f45a12f437a164f51ff",
          "sha1": "ca6475af58d948062e48170ec303a3bc0f4eb584",
          "md5": "cdcc920baf76ddc8909360f4dc1635ff"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobimap_plugin_debug-1.0.aar",
          "url": "mobimap_plugin_debug-1.0.aar",
          "size": 469234,
          "sha512": "5640a56735045f7c86f5ce30589171e98079d92504fec5ecd6e6585be67c1993ad4eca25da1ca5d2d7c08a5f4668601472467d8d4deb1ee5d3ba04cf45ff312d",
          "sha256": "924240212eb01db887900d4da4bb6784bbe4017ee1156f45a12f437a164f51ff",
          "sha1": "ca6475af58d948062e48170ec303a3bc0f4eb584",
          "md5": "cdcc920baf76ddc8909360f4dc1635ff"
        }
      ]
    }
  ]
}
