{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.crashlytics",
    "module": "firebase_crashlytics_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_crashlytics_release-1.0.aar",
          "url": "firebase_crashlytics_release-1.0.aar",
          "size": 16445,
          "sha512": "5d7f67b58c1c676ce1d86551a4c7bc0ce35b84bf02324edac12a7ea463ba69ffd61fa264827dd4b42b3b1b91c48d1b40102c065f8f9785015185ed6464025990",
          "sha256": "abf8472786a4770637f871cee4cff95e0a0ac9b17727ec3fa3c5b380694dbaba",
          "sha1": "e538703665d1f0c45f811446a12357c98f2aa16a",
          "md5": "f2b71cd40c744a9766399ad8c519a5ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "30.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_crashlytics_release-1.0.aar",
          "url": "firebase_crashlytics_release-1.0.aar",
          "size": 16445,
          "sha512": "5d7f67b58c1c676ce1d86551a4c7bc0ce35b84bf02324edac12a7ea463ba69ffd61fa264827dd4b42b3b1b91c48d1b40102c065f8f9785015185ed6464025990",
          "sha256": "abf8472786a4770637f871cee4cff95e0a0ac9b17727ec3fa3c5b380694dbaba",
          "sha1": "e538703665d1f0c45f811446a12357c98f2aa16a",
          "md5": "f2b71cd40c744a9766399ad8c519a5ff"
        }
      ]
    }
  ]
}
